### ISSUE TITLE
Improvments: Demo and more

### ISSUE THREAD

**Issue by thehackingman** [jarves/jarves#11]
Hello,
I tried your cms, it's so amazing!
I just think if you setup a demo, it would be amazing for my clients!
Have you a facebook page or twitter account about jarves?

Thanks

**Comment by xyNNN** [comment]
There is a demo already, please have a look at demo.jarves.io
Also have a look at our facebook fanpage https://www.facebook.com/Jarves.io/

Greets,
xyNNN

**Comment by thehackingman** [comment]
Thank you! :)
