### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by nchamsi** [jarves/jarves#15]
{
    "status": 500,
    "error": "InvalidArgumentException",
    "message": "The \"\/C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\/Resources\/public\/admin\/js\/mootools-extras\" directory does not exist.",
    "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Finder\\Finder.php",
    "line": 546,
    "trace": [
        {
            "function": "in",
            "class": "Symfony\\Component\\Finder\\Finder",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Configuration\\Assets.php",
            "line": 162,
            "type": "->",
            "args": [
                "string"
            ]
        },
        {
            "function": "getAssets",
            "class": "Jarves\\Configuration\\Assets",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Configuration\\Assets.php",
            "line": 181,
            "type": "->",
            "args": []
        },
        {
            "function": "getIterator",
            "class": "Jarves\\Configuration\\Assets",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Configuration\\Bundle.php",
            "line": 697,
            "type": "->",
            "args": []
        },
        {
            "function": "collectAssets",
            "class": "Jarves\\Configuration\\Bundle",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Configuration\\Bundle.php",
            "line": 713,
            "type": "->",
            "args": [
                "array"
            ]
        },
        {
            "function": "getAdminAssetsInfo",
            "class": "Jarves\\Configuration\\Bundle",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Admin\\AdminAssets.php",
            "line": 130,
            "type": "->",
            "args": []
        },
        {
            "function": "addMainResources",
            "class": "Jarves\\Admin\\AdminAssets",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\jarves\\jarves\\Controller\\AdminLoginController.php",
            "line": 41,
            "type": "->",
            "args": []
        },
        {
            "function": "showLoginAction",
            "class": "Jarves\\Controller\\AdminLoginController",
            "file": null,
            "line": null,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "call_user_func_array",
            "class": null,
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\var\\cache\\dev\\classes.php",
            "line": 4898,
            "type": null,
            "args": [
                "array",
                "array"
            ]
        },
        {
            "function": "handleRaw",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\var\\cache\\dev\\classes.php",
            "line": 4853,
            "type": "->",
            "args": [
                "object",
                "integer"
            ]
        },
        {
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Kernel.php",
            "line": 168,
            "type": "->",
            "args": [
                "object",
                "integer",
                "boolean"
            ]
        },
        {
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\web\\app_dev.php",
            "line": 28,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "require",
            "class": null,
            "file": "C:\\xampp\\htdocs\\website-with-jarves\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Resources\\config\\router_dev.php",
            "line": 40,
            "type": null,
            "args": [
                "string"
            ]
        }
    ]
}

**Comment by xyNNN** [comment]
Sorry mate, we don't support windows :( Please use our vagrant (see https://github.com/jarves/jarves-vagrant)
