### ISSUE TITLE
jarves:configuration:database

### ISSUE THREAD

**Issue by bishoymelek** [jarves/jarves#17]
Hello ,
I heard about jarves from a friend and trying to install it to start using it but I got an error within the "Configurate database settings" step 
when i try :  php bin/console jarves:configuration:database --help

it gives me : 
[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "jarves:configuration:database" is not defined.
Did you mean this?
    jarves:configuration:travis

what to do to fix it ?
thank you

**Comment by mablae** [comment]
Hi @bishoymelek , 

Looks like an bug in the docs. There is no such Command in the Codebase atm .

Please just edit config/parameters.yml manually to setup you database credentials like mentioned in the docs here: http://jarves.io/documentation/quick-start/installation#3._Configurate_database_settings

**Comment by bishoymelek** [comment]
hello dear , 
look here is my parameters.yml and it should be working!

# This file is auto-generated during the composer install
parameters:
    database_driver: mysql
    database_host: localhost
    database_port: null
    database_name: symfony <as i created it>
    database_user:  <my user name on db >
    database_password:  <my pass of my user on the db>
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt

**Comment by mablae** [comment]
Do you get an error message?

**Comment by bishoymelek** [comment]
yes i get the following : 
 [Symfony\Component\Console\Exception\CommandNotFoundException]
 Command "jarves:configuration:database" is not defined.
 Did you mean this?
     jarves:configuration:travis

**Comment by mablae** [comment]
No. 

What is your CURRENT error? We already solved there is no such command.

**Comment by bishoymelek** [comment]
I'm sorry for being dummy :)) i finished now everything , but when i run it it opens symfony and this error msg : Cant render view `JarvesDemoThemeBundle:Layout:default.html.twig` of theme `jarvesDemoTheme`.
can you let me know how to fix this ?

the error is : CRITICAL - Uncaught PHP Exception Exception: "Cant render view `JarvesDemoThemeBundle:Layout:default.html.twig` of theme `jarvesDemoTheme`." at C:\wamp\www\my_project_name\vendor\jarves\jarves\PageResponse.php line 718

**Comment by mablae** [comment]
Did you run that in `dev` environment? What does `app/logs/error.log` say? 
Please try to follow the install instructions for `jarvis-standard`.

**Comment by bishoymelek** [comment]
I can't find app/logs/error.log . but i followed all the step 
Javris standard gives me same error !

**Comment by mablae** [comment]
Without an error message, I can not help, sorry.

**Comment by bishoymelek** [comment]
![ffdfdsf](https://cloud.githubusercontent.com/assets/18382348/22187381/02c56af0-e10e-11e6-91a9-1726fafe41ff.png)

**Comment by mablae** [comment]
Looks like a bug not related to database at all. 

A template File is not found in the right location. Did you enable all the required bundles in app/AppKernel.php?

**Comment by bishoymelek** [comment]
I think so , here is the code : 

<?php
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;
class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
        // our dependencies - it's important that these come before Jarves
        new Propel\Bundle\PropelBundle\PropelBundle(),
        new FOS\RestBundle\FOSRestBundle(),
        new Nelmio\ApiDocBundle\NelmioApiDocBundle(),
        new Jarves\JarvesBundle(),
        new Jarves\DemoTheme\JarvesDemoThemeBundle(),
        new Jarves\Publication\JarvesPublicationBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
        }
        return $bundles;
    }

    public function getRootDir()
    {
        return __DIR__;
    }

    public function getCacheDir()
    {
        return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        return dirname(__DIR__).'/var/logs';
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }
}

**Comment by bishoymelek** [comment]
I think so , here is the code  : `<?php

use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
        // our dependencies - it's important that these come before Jarves
        new Propel\Bundle\PropelBundle\PropelBundle(),
        new FOS\RestBundle\FOSRestBundle(),
        new Nelmio\ApiDocBundle\NelmioApiDocBundle(),
        new Jarves\JarvesBundle(),
        new Jarves\DemoTheme\JarvesDemoThemeBundle(),
        new Jarves\Publication\JarvesPublicationBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
        }

        return $bundles;
    }

    public function getRootDir()
    {
        return __DIR__;
    }

    public function getCacheDir()
    {
        return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        return dirname(__DIR__).'/var/logs';
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }
}`

**Comment by marcj** [comment]
That file exists in the repo https://github.com/jarves/jarves/blob/master/Resources/views/Default/navigation.html.twig. Can you check that you have the file in `vendor/jarves/jarves/Resources/views/Default/navigation.html.twig`?

**Comment by marcj** [comment]
Command `jarves:configuration:database` has been removed since we use Symfony's configuration system now. Docs updated needed.

**Comment by bishoymelek** [comment]
now i get the following :
CRITICAL - Class 'Jarves\PageResponse' not found 
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "PageResponse" from namespace "Jarves". Did you forget a "use" statement for another namespace?" at C:\wamp\www\my_project_name\vendor\jarves\jarves\PageResponseFactory.php line 97 

I'm sorry guys about all these questions but I'm trying to install it

**Comment by mablae** [comment]
@bishoymelek It's alpha material :) - If you are looking for an production ready CMS you should probably 
use something else with a bigger community.

**Comment by bishoymelek** [comment]
I know and I hope I can use it :) just one last question , is this a bug ?
CRITICAL - Uncaught PHP Exception InvalidArgumentException: "The "/C:\wamp\www\website-with-jarves\vendor\jarves\jarves/Resources/public/admin/js/mootools-extras" directory does not exist." at C:\wamp\www\website-with-jarves\vendor\symfony\symfony\src\Symfony\Component\Finder\Finder.php line 546

**Comment by marcj** [comment]
All these files and folders exist for a very long time. I have no idea why it doesn't work on your machine. Probably windows related as windows it not supported.

**Comment by bishoymelek** [comment]
I will use linux and try it , thanks a lot :)
