### ISSUE TITLE
JarvesExtension Exception

### ISSUE THREAD

**Issue by Audax23** [jarves/jarves#2]
Hello Marc,

I'm very excited to test your app, i've succesfully install via composer, but now i've this exception when i launch the command to build model 
(php app/console propel:model:build), i don't know if i've done all requirements of the config.
Can you help me to resolve this, please.
Thank you!

[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                         
  Catchable Fatal Error: Argument 2 passed to Jarves\Configuration\Model::__construct() must be an instance of Jarves\Jarves, instance of Jarves\DependencyInjection\JarvesExtension given, called  
   in /Applications/MAMP/htdocs/jarves/src/Jarves/DependencyInjection/JarvesExtension.php on line 105 and defined

**Comment by marcj** [comment]
Thanks, I've fixed it in current master. Would you please try it again?

**Comment by Audax23** [comment]
perfect! exception disappeared.  
thank you Marc
