### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by maiorano84** [jarves/jarves#22]
I was interested in checking this out, but it appears [your website](http://jarves.io/) has been down for the past few days.

Any plans in getting it back up? Or at least migrating the site documentation to the README?

**Comment by marcj** [comment]
> Any plans in getting it back up?

Actually, not really. It costs me too much money and I didn't find a new maintainer for months.

**Comment by maiorano84** [comment]
That's a shame. The screenshots look like this had quite a bit of polish.

Hopefully your financial situation changes. [DigitalOcean](https://www.digitalocean.com/pricing/) has some great pricing if you know how to manage a server yourself.
