### ISSUE TITLE
The service "jarves.configuration.database.connection.main" has a dependency on a non-existent parameter "database_driver".

### ISSUE THREAD

**Issue by MiguelFB** [jarves/jarves#5]
Hello,

I am trying to install your app on my Windows environment, but when I try to run composer update, I keep getting the following error:

The service "jarves.configuration.database.connection.main" has a dependency on a non-existent parameter "database_driver".  Did you mean one of these: "database_name", "database_user"?

I'm confused as to why this is happening, being that database_drive is a legit parameter. 
Also, before this I was getting a different error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - propel/propel dev-master requires php >=5.5 -> your PHP version (5.6.14) or "config.platform.php" value does not satisfy that requirement.
    - propel/propel dev-master requires php >=5.5 -> your PHP version (5.6.14) or "config.platform.php" value does not satisfy that requirement.
    - Installation request for propel/propel dev-master -> satisfiable by propel/propel[dev-master].

I fixed this by removing:    
"platform": {
            "php": "5.3.9"
        }
from composer.json

**Comment by marcj** [comment]
You need to add `database_driver` in your `paramters.yml`, I guess newer Symfony versions aren't needing it anymore.

example: 

```yaml
parameters:
    database_driver: mysql
```

**Comment by MiguelFB** [comment]
Thanks for the quick answer. I had already tried that, but the file was overwritten every time I ran composer update. I had to add the same parameter to the file parameters.yml.dist to fix this problem.

Now I'm getting another error:

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: symlink(): Cannot create symlink, error code(1314)

But I suspect this has to do with permissions. I'll investigate this one. Thanks!

**Comment by marcj** [comment]
Are you using windows? Never tried the symlink stuff on windows, since I really wouldn't want to support windows. :P Either it's a permission issue on the filesystem or windows needs administration privilege as some other threads at various github repos indicate it.

**Comment by MiguelFB** [comment]
Yeah that error was specific to running cmd and Apache in non-admin mode. (code 1314).
I fixed that, but now I am getting error 183

Warning: symlink(): Cannot create symlink, error code(183)

There isn't a whole lot of info about this out there, but it seems it has to do with how the file system paths are defined. I would need to manually create a symlink for it to work, but since this process is tied to composer, I don't know what exactly I'd need to do to get it to work. I'm probably going to install Ubuntu on this machine over the weekend and give it a try.

**Comment by marcj** [comment]
It's probably the best to install Linux in a VM since Jarves is actually only ever used on *nix systems.

**Comment by MiguelFB** [comment]
Yeah, I'll give VM a try before then. Thanks for you help. Your app looks great by the way, hopefully I can get it to work soon :)

**Comment by MiguelFB** [comment]
Hey,

I'm on a Mac now. I am getting this error when running composer update:


Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

                                                                                                                                                                                                                                                                                                                                                                                                                                    
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                                                                                                                                                                                                                                         
  Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.  
                                                                                                                                                                                                                                                                                                                                                                                                                                    

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                                                 
  [RuntimeException]                                                                                                             
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                      
                                                                                                                                                                                                                                            
    [Symfony\Component\Debug\Exception\ContextErrorException]                                                                    
                                                                                                                                                                                                                                                            
    Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required*           
  to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you a  
  re still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, bu  
  t please set date.timezone to select your timezone.

**Comment by marcj** [comment]
Your php needs a default timezone: http://hints.macworld.com/article.php?story=20090831101932728

**Comment by MiguelFB** [comment]
Thanks, that was an easy fix. I am struggling a little bit with this one:

PHP Fatal error:  Call to a member function getGroupPermission() on a non-object in /Users/rodrigoserzedello/website-with-jarves/src/Jarves/Filesystem/Adapter/Local.php on line 141
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
                                                                                                                                 
  [RuntimeException]                                                                                                             
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                      
  PHP Fatal error:  Call to a member function getGroupPermission() on a non-object in /Users/rodrigoserzedello/website-with-jar  
  ves/src/Jarves/Filesystem/Adapter/Local.php on line 141  

Could this also be related to my local php settings?

**Comment by marcj** [comment]
well that seems to be the case when you haven't copied the config.jarves.xml to the correct place as its written in the installation docu: https://github.com/jarves/jarves/blob/master/Resources/doc/installation.md Try this with the config file and clear the cache

**Comment by MiguelFB** [comment]
Ok yeah in the installation guide copying the config.jarves.xml file is a step after running composer update for the first time (after adding the dependencies). Copying the file config.jarves.xml removed the previous error on composer update.

This error is now showing up:

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-update-cmd event terminated with an exception

                                                                                                     
  [RuntimeException]                                                                                 
  An error occurred when executing the "'assets:install --symlink --relative '\''web'\'''" command:  
                                                                                                     
    [Symfony\Component\Debug\Exception\ContextErrorException]                                        
    Warning: chgrp(): Unable to find gid for www-data                                                
                                                                                                     
It seems to still be related to group permissions.

**Comment by marcj** [comment]
since you're on a OSX machine you need to change the group file owner of newly created files by Jarves by changing the config.jarves.xml a bit, you find there `www-data`, change it to your webserver's group, often `_www` or `staff`, but I honestly don't know what server you're running. if you use `php app/console server:run` you need to add there a group your current user belongs to, which is mostly `staff` (you see it by running `groups` in the console) on OSX.

**Comment by MiguelFB** [comment]
Ok, awesome, it works now :) Changing it to staff fixed it (using mamp server).

 [OK] All assets were successfully installed.     

Thanks!

**Comment by MiguelFB** [comment]
Ah not done yet. On step 4, when I run this command:

`php app/console propel:model:build`

I get this message:
                                                                  
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "propel:model" namespace.  
```

**Comment by marcj** [comment]
Oh, I forgot to add PropelBundle to AppKernel: https://github.com/jarves/jarves/commit/94a406fd8fece9577409ab81121559348ec387bd

**Comment by MiguelFB** [comment]
Ok it works. Setting up DB now.

**Comment by MiguelFB** [comment]
Cool the site is up and running locally. Thanks again!

**Comment by MiguelFB** [comment]
Hey, did I miss something on my db schema migration?

I'm getting this when I try to access the admin section:

Unknown column Slug in model Jarves\Publication\Model\News
500 Internal Server Error - UnknownColumnException
```

Stack Trace
in vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php at line 2064   -
    protected function getRealColumnName($columnName)
    {
        if (!$this->getTableMap()->hasColumnByPhpName($columnName)) {
            throw new UnknownColumnException('Unknown column ' . $columnName . ' in model ' . $this->modelName);
        }
        if ($this->useAliasInSQL) {
at ModelCriteria ->getRealColumnName ('Slug') 
in vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php at line 133   + 
at ModelCriteria ->filterBy ('Slug', 'jarves') 
```

**Comment by marcj** [comment]
Looks like you fired `php app/console jarves:orm:build:propel JarvesPublication` which overrides `src/Jarves/Publication/Resources/config/schema/publication_news.schema.xml` and with it the Propel's Slug behavior. I just saw that those files aren't in the git repo and also saw I haven't pushed the latest change where I did add those files... so I'll pushed it.
Please pull Jarves/Publication again and don't call `php app/console jarves:orm:build:propel xy` :)

**Comment by MiguelFB** [comment]
I did a git pull on Jarves Publication. I can see I have the files:
publication_news.schema.xml		
publication_news_comment.schema.xml	
publication_news_intro.schema.xml
publication_news_category.schema.xml	
publication_news_content.schema.xml

I cleared the cache, and did not `run php app/console jarves:orm:build:propel`
but Im still getting the same error.

**Comment by marcj** [comment]
You need now to rebuild Propel ORM and database stuff:

```bash
php app/console propel:model:build #build base model

php app/console propel:migration:diff #generates a database schema diff
php app/console propel:migration:up #upgrade the database schema
```

**Comment by MiguelFB** [comment]
Got ya. That worked : D

**Comment by marcj** [comment]
Nice! It's a bit tricky to get all things running since many libraries/patterns are involved in Jarves.

**Comment by MiguelFB** [comment]
Yeah, and I'm fairly new to Symfony.. still learning all the intricacies. 
Btw, I can access most of the admin area, except for User Management -> Groups
I'm getting the following error:

`Failed. Error Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "OPTIONS /jarves/object/jarves/groups/" (from http://127.0.0.1:8000/jarves)`

**Comment by marcj** [comment]
Yeah that seems to be some alpha material errors. I guess there is somewhere a typo, because the route is actually `jarves/object/jarves/group` without leading `s`. (Found the bug already: https://github.com/jarves/jarves/blob/master/Resources/config/jarves.entrypoints.xml#L129-L131), try to adjust there `object="jarves/groups"` to `object="jarves/group"`). If it runs a Pull-request would awesome :P

**Comment by MiguelFB** [comment]
Yeah that did it.

**Comment by marcj** [comment]
I fixed a ton of bugs lately, so I closed this. Feel free to open new issues :+1: :)

**Comment by CyDoor** [comment]
Hey, first -> SICK CMS! Love it diretly
@all:
I had 5 min ago the same issue running:
WIN10 64x

Error:
  [RuntimeException]                                                         
  An error occurred when executing the ""cache:clear --no-warmup"" command:  
                                                                 
    [Symfony\Component\Debug\Exception\ContextErrorException]    
    Warning: symlink(): Cannot create symlink, error code(1314) 


Solution -> start the cmd as Administrator (right click "run as admin")
